// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const host = process.env.host || "localhost";
const port = process.env.port || "5432";
const user = process.env.user || "postgres";
const password = process.env.password || "";
const database = process.env.database || "";

const databaseUrl = (process.env.DATABASE_URL) as string 

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
